#define CLK 4
#define OUT 3
#define LD 2
#define ANALOG_SELECT_0 8
#define ANALOG_SELECT_1 9
#define KEYBOARD_LENGHT 100
#define ANALOG_LENGHT 16
#define midi true
#define t 1
#define tAnalog 1

#define ANALOG_DELTA 10


bool keyStatus[KEYBOARD_LENGHT];

int analogVal[ANALOG_LENGHT];
int newAnalogVal[ANALOG_LENGHT];

// ADDRESS DEFINITION

//slider panel
#define ANALOG_PEDAL_VOLUME 5
#define ANALOG_UPPER_SUSTAIN 9
#define ANALOG_KEYBOARD_BALANCE 1
#define ANALOG_PRESET_PERCUSS_VOLUME 12
#define ANALOG_VIBRATO_SPEED 4
#define ANALOG_REPEAT_SPEED 8
#define ANALOG_SYNT_PRESET_VOLUME 0

//computer Band
#define ANALOG_BASS_VOLUME 13
#define ANALOG_CHORD_VOLUME 2
#define ANALOG_MULTI_P_VOLUME 10
#define ANALOG_RHYTHM_VOLUME 6
#define ANALOG_TEMPO 14

//other
#define ANALOG_SYNT_PRESETS_TUNING 3
#define ANALOG_GENERAL_TUNING 11
#define ANALOG_GENERAL_VOLUME 7
